### ISSUE TITLE
A(link) tag on the entire "about" description in your github page.

### ISSUE THREAD

**Issue by florian-s-code** [sanojian/cellauto#1]
This may not be the best way to report this, but there is a markup problem in your index.html.
There is several seemingly misplaced &lt;a&gt; tags around text. There is no href so it's not usable and invalid ([w3c validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fsanojian.github.io%2Fcellauto%2F))
It's visible only on the "about" paragraph (underlined on hover) but the "usage" paragraph is also in a &lt;a&gt; tag.
It seemed strange to do a pull request on a github page but I can do it if you want. 

The library itself looks really practical and powerful. I have not found a use for now, but I keep it at hand. !

**Comment by sanojian** [comment]
Thanks, I had used the anchor incorrectly.
