### ISSUE TITLE
Using a png as a world generator

### ISSUE THREAD

**Issue by forresthopkinsa** [sanojian/cellauto#8]
Hi, I was wondering if it was possible to use CellAuto using a CAWorld that is not procedurally generated?

For example, I want to use an isometric cube as the world for my automata. How would I go about that? Thanks.

**Comment by sanojian** [comment]
Do you want to run a 3D world simulation?  Cellauto does not currently support 3D worlds.  It supports 2D maps with square or hexagononal grids.

To answer the other part of your question, you can use a PNG as the source of your world but you will need to convert it into an array first.  Then use the "initializeFromGrid" api command to generate the world.

**Comment by forresthopkinsa** [comment]
I'm talking about using this kind of an image as the CAworld. And OK, got
it.

**Comment by forresthopkinsa** [comment]
oops, it didn't paste the image. here:

http://www.deimel.org/images/plain_cube.gif
